services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - gitea
      - grafana
      - authelia

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
    restart: always

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  authelia:
    image: authelia/authelia:latest
    volumes:
      - ./authelia:/config
    command: authelia --config /config/configuration.yml
    ports:
      - "9091:9091"

  loki:
    image: grafana/loki:2.6.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  gitea_data:
  grafana_data:
  loki_data:
